language: ruby
rvm:
  - 2.4.1
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - awesome_bot README.md --allow-dupe --allow-redirect --allow-ssl --allow-timeout --white-list https://cloud.oracle.com/commerce-cloud
notifications:
  email: false